[2023-05-29T18:45:38.802+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_test_dag1.extract_data manual__2023-05-29T18:45:35.284866+00:00 [queued]>
[2023-05-29T18:45:38.815+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_test_dag1.extract_data manual__2023-05-29T18:45:35.284866+00:00 [queued]>
[2023-05-29T18:45:38.815+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-05-29T18:45:38.842+0000] {taskinstance.py:1327} INFO - Executing <Task(MySqlOperator): extract_data> on 2023-05-29 18:45:35.284866+00:00
[2023-05-29T18:45:38.847+0000] {standard_task_runner.py:57} INFO - Started process 199 to run task
[2023-05-29T18:45:38.852+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'mysql_test_dag1', 'extract_data', 'manual__2023-05-29T18:45:35.284866+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/second_dag.py', '--cfg-path', '/tmp/tmprhztdywn']
[2023-05-29T18:45:38.855+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask extract_data
[2023-05-29T18:45:38.992+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_test_dag1.extract_data manual__2023-05-29T18:45:35.284866+00:00 [running]> on host d9c4e9218ccd
[2023-05-29T18:45:39.175+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mysql_test_dag1' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-05-29T18:45:35.284866+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-29T18:45:35.284866+00:00'
[2023-05-29T18:45:39.176+0000] {sql.py:262} INFO - Executing: SELECT * FROM employees;
[2023-05-29T18:45:39.191+0000] {base.py:73} INFO - Using connection ID 'hrms' for task execution.
[2023-05-29T18:45:39.413+0000] {base.py:73} INFO - Using connection ID 'hrms' for task execution.
[2023-05-29T18:45:39.419+0000] {sql.py:375} INFO - Running statement: SELECT * FROM employees;, parameters: None
[2023-05-29T18:45:39.420+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'employees.employees' doesn't exist")
[2023-05-29T18:45:39.433+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=mysql_test_dag1, task_id=extract_data, execution_date=20230529T184535, start_date=20230529T184538, end_date=20230529T184539
[2023-05-29T18:45:39.462+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 18 for task extract_data ((1146, "Table 'employees.employees' doesn't exist"); 199)
[2023-05-29T18:45:39.510+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-29T18:45:39.566+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
