[2023-05-30T04:01:01.733+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.send_email scheduled__2023-05-20T00:00:00+00:00 [queued]>
[2023-05-30T04:01:01.772+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.send_email scheduled__2023-05-20T00:00:00+00:00 [queued]>
[2023-05-30T04:01:01.773+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-05-30T04:01:01.873+0000] {taskinstance.py:1327} INFO - Executing <Task(EmailOperator): send_email> on 2023-05-20 00:00:00+00:00
[2023-05-30T04:01:01.887+0000] {standard_task_runner.py:57} INFO - Started process 375 to run task
[2023-05-30T04:01:01.905+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'send_email', 'scheduled__2023-05-20T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/smtp_test.py', '--cfg-path', '/tmp/tmpldoh1urh']
[2023-05-30T04:01:01.918+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask send_email
[2023-05-30T04:01:02.142+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.send_email scheduled__2023-05-20T00:00:00+00:00 [running]> on host d6193d7ff462
[2023-05-30T04:01:02.587+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shahsoumil519@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2023-05-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-20T00:00:00+00:00'
[2023-05-30T04:01:02.672+0000] {logging_mixin.py:149} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py:152 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-05-30T04:01:02.673+0000] {configuration.py:676} WARNING - section/key [smtp/smtp_user] not found in config
[2023-05-30T04:01:02.679+0000] {email.py:268} INFO - Email alerting: attempt 1
[2023-05-30T04:01:02.684+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-05-30T04:01:02.708+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=send_email, execution_date=20230520T000000, start_date=20230530T040101, end_date=20230530T040102
[2023-05-30T04:01:02.764+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 72 for task send_email ([Errno 99] Cannot assign requested address; 375)
[2023-05-30T04:01:02.788+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-30T04:01:02.964+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
